export const mentorList = [
  {
    fullName: 'Phạm Hoàng Tuấn',
    email: 'phamhoangtuanqn@gmail.com',
    phone: '0812665001',
    username: 'htuanqn',
    role: 'MENTOR',
    facebook: 'https://www.facebook.com/phamhoangtuanqn/',
  },
  {
    fullName: 'Nguyễn Hoàng Minh',
    email: 'nguyenminh150906@gmail.com',
    phone: '0911850906',
    username: 'hming4222',
    role: 'MENTOR',
    facebook: 'https://www.facebook.com/minh.nguyenthien.583/',
  },
  {
    fullName: 'Đào Thị Út Trinh',
    email: 'uttrinh4115@gmail.com',
    phone: '0901928382',
    username: 'ckjnn',
    role: 'MENTOR',
    facebook: 'https://www.facebook.com/ckjnn',
  },
  {
    fullName: 'Nguyễn Huy Phong',
    email: 'touman876@gmail.com',
    phone: '0389584993',
    username: 'satou_arashi_876',
    role: 'MENTOR',
    facebook: 'https://www.facebook.com/huy.phong.73997861',
  },
  {
    fullName: 'Nguyễn Đức Bảo Lâm',
    email: 'lam01662052827@gmail.com',
    phone: '0327089143',
    username: 'baolamde',
    role: 'MENTOR',
    facebook: 'https://www.facebook.com/ndblam/',
  },
  {
    fullName: 'Nguyễn Đức Huy',
    email: 'nguyenduchuy23052006@gmail.com',
    phone: '0399692306',
    username: 'jameshiiii06',
    role: 'MENTOR',
    facebook: 'https://www.facebook.com/jameshiii06',
  },
  {
    fullName: 'Võ Gia Huy',
    email: 'huyvog6226@gmail.com',
    phone: '0961002445',
    username: 'hank_74252',
    role: 'MENTOR',
    facebook: 'https://www.facebook.com/vo.gia.huy.622929',
  },
  {
    fullName: 'Hoàng Đình Quang',
    email: 'quanghd023@gmail.com',
    phone: '0347247657',
    username: 'kwamk',
    role: 'MENTOR',
    facebook: 'https://www.facebook.com/aloha.alola.75/',
  },
  {
    fullName: 'Võ Đức Trí',
    email: 'voductri88714@gmail.com',
    phone: '0337294360',
    username: 'trisvd',
    role: 'MENTOR',
    facebook: 'https://www.facebook.com/tri.uc.vo/',
  },
  {
    fullName: 'Phan Chí Thuận',
    email: 'tcp352006@gmail.com',
    phone: '0943063424',
    username: 'thuanphansodope',
    role: 'MENTOR',
    facebook: 'https://www.facebook.com/phnchthn/',
  },
  {
    fullName: 'Hoàng Thị Khánh Linh',
    email: 'khanhlinhwork1110@gmail.com',
    phone: '0327897344',
    username: 'khanhlinh0209',
    role: 'MENTOR',
    facebook: 'https://www.facebook.com/khanhlinh0209205',
  },
];
console.log(mentorList.length);
