export const roomList = [
  {
    group: 12,
    room_number: 'Google Meet',
    start_time: '2026-01-17T19:05:00Z',
    end_time: '2026-01-17T19:50:00Z',
    mode_present: 'ONLINE',
    present_phase: 'TRIAL',
  },
  {
    group: 9,
    room_number: 'Google Meet',
    start_time: '2026-01-17T20:05:00Z',
    end_time: '2026-01-17T20:50:00Z',
    mode_present: 'ONLINE',
    present_phase: 'TRIAL',
  },
  {
    group: 8,
    room_number: 'Google Meet',
    start_time: '2026-01-18T19:05:00Z',
    end_time: '2026-01-18T19:50:00Z',
    mode_present: 'ONLINE',
    present_phase: 'TRIAL',
  },
  {
    group: 3,
    room_number: 'Google Meet',
    start_time: '2026-01-18T20:05:00Z',
    end_time: '2026-01-18T20:50:00Z',
    mode_present: 'ONLINE',
    present_phase: 'TRIAL',
  },
  {
    group: 13,
    room_number: 'Google Meet',
    start_time: '2026-01-19T19:05:00Z',
    end_time: '2026-01-19T19:50:00Z',
    mode_present: 'ONLINE',
    present_phase: 'TRIAL',
  },
  {
    group: 14,
    room_number: 'Google Meet',
    start_time: '2026-01-19T20:05:00Z',
    end_time: '2026-01-19T20:50:00Z',
    mode_present: 'ONLINE',
    present_phase: 'TRIAL',
  },
  {
    group: 7,
    room_number: 'Google Meet',
    start_time: '2026-01-20T19:05:00Z',
    end_time: '2026-01-20T19:50:00Z',
    mode_present: 'ONLINE',
    present_phase: 'TRIAL',
  },
  {
    group: 5,
    room_number: 'Google Meet',
    start_time: '2026-01-20T20:05:00Z',
    end_time: '2026-01-20T20:50:00Z',
    mode_present: 'ONLINE',
    present_phase: 'TRIAL',
  },
  {
    group: 2,
    room_number: 'Google Meet',
    start_time: '2026-01-21T19:05:00Z',
    end_time: '2026-01-21T19:50:00Z',
    mode_present: 'ONLINE',
    present_phase: 'TRIAL',
  },
  {
    group: 11,
    room_number: 'Google Meet',
    start_time: '2026-01-21T20:05:00Z',
    end_time: '2026-01-21T20:50:00Z',
    mode_present: 'ONLINE',
    present_phase: 'TRIAL',
  },
];
console.log(roomList.length);

export const judgeRooms = {
  12: [
    { fullName: 'Nguyễn Hoàng Minh', email: 'nguyenminh150906@gmail.com' },
    { fullName: 'Phạm Hoàng Tuấn', email: 'phamhoangtuanqn@gmail.com' },
    { fullName: 'Võ Nhật Minh', email: 'nhatminhvo2311@gmail.com' },
    { fullName: 'Trương Đoàn Viên', email: 'vientruongdoan@gmail.com' },
    { fullName: 'Thuận Phan', email: 'tcp352006@gmail.com' },
    { fullName: 'Dương Ngô', email: 'duongngo2209@gmail.com' },
    { fullName: 'Phạm Đức Phúc', email: 'ducphucdn2006@gmail.com' },
    { fullName: 'Huỳnh Minh Khang', email: 'khanghuynh0245@gmail.com' },
  ],
  9: [
    { fullName: 'Nguyễn Hoàng Minh', email: 'nguyenminh150906@gmail.com' },
    { fullName: 'Phạm Hoàng Tuấn', email: 'phamhoangtuanqn@gmail.com' },
    { fullName: 'Nguyễn Tuấn Vinh', email: 'tuanvinh2402@gmail.com' },
    { fullName: 'Võ Nhật Minh', email: 'nhatminhvo2311@gmail.com' },
    { fullName: 'Võ Đức Trí', email: 'voductri88714@gmail.com' },
    { fullName: 'Thuận Phan', email: 'tcp352006@gmail.com' },
    { fullName: 'Dương Ngô', email: 'duongngo2209@gmail.com' },
    { fullName: 'Huỳnh Minh Khang', email: 'khanghuynh0245@gmail.com' },
  ],
  8: [
    { fullName: 'Nguyễn Huy Phong', email: 'touman876@gmail.com' },
    { fullName: 'Đào Thị Út Trinh', email: 'uttrinh4115@gmail.com' },
    { fullName: 'Trần Trọng Nghĩa', email: 'hs23t2@gmail.com' },
    { fullName: 'Võ Nhật Minh', email: 'nhatminhvo2311@gmail.com' },
    { fullName: 'Nguyễn Tuấn Vinh', email: 'tuanvinh2402@gmail.com' },
    { fullName: 'Phạm Hoàng Tuấn', email: 'phamhoangtuanqn@gmail.com' },
    { fullName: 'Trương Đoàn Viên', email: 'vientruongdoan@gmail.com' },
    { fullName: 'Nguyễn Đoàn Nhật Đăng', email: 'nhatdang23092006@gmail.com' },
    { fullName: 'Huỳnh Hân Đồng', email: 'huynhhandong@gmail.com' },
    { fullName: 'Huỳnh Minh Khang', email: 'khanghuynh0245@gmail.com' },
  ],
  3: [
    { fullName: 'Nguyễn Huy Phong', email: 'touman876@gmail.com' },
    { fullName: 'Trần Trọng Nghĩa', email: 'hs23t2@gmail.com' },
    { fullName: 'Võ Nhật Minh', email: 'nhatminhvo2311@gmail.com' },
    { fullName: 'Nguyễn Tuấn Vinh', email: 'tuanvinh2402@gmail.com' },
    { fullName: 'Phạm Hoàng Tuấn', email: 'phamhoangtuanqn@gmail.com' },
    { fullName: 'Trương Đoàn Viên', email: 'vientruongdoan@gmail.com' },
    { fullName: 'Nguyễn Đoàn Nhật Đăng', email: 'nhatdang23092006@gmail.com' },
    { fullName: 'Huỳnh Hân Đồng', email: 'huynhhandong@gmail.com' },
    { fullName: 'Huỳnh Minh Khang', email: 'khanghuynh0245@gmail.com' },
  ],
  13: [
    { fullName: 'Hoàng Thị Khánh Linh', email: 'khanhlinhwork1110@gmail.com' },
    { fullName: 'Phạm Đức Phúc', email: 'ducphucdn2006@gmail.com' },
    { fullName: 'Nguyễn Tuấn Vinh', email: 'tuanvinh2402@gmail.com' },
    { fullName: 'Nguyễn Đức Bảo Lâm', email: 'lam01662052827@gmail.com' },
    { fullName: 'Nguyễn Đức Huy', email: 'quanvu1497163@gmail.com' },
    { fullName: 'Trương Đoàn Viên', email: 'vientruongdoan@gmail.com' },
    { fullName: 'Nguyễn Huy Phong', email: 'touman876@gmail.com' },
    { fullName: 'Nguyễn Đoàn Nhật Đăng', email: 'nhatdang23092006@gmail.com' },
    { fullName: 'Võ Gia Huy', email: 'huyvog6226@gmail.com' },
    { fullName: 'Võ Đức Trí', email: 'voductri88714@gmail.com' },
  ],
  14: [
    { fullName: 'Hoàng Thị Khánh Linh', email: 'khanhlinhwork1110@gmail.com' },
    { fullName: 'Phạm Đức Phúc', email: 'ducphucdn2006@gmail.com' },
    { fullName: 'Trần Trọng Nghĩa', email: 'hs23t2@gmail.com' },
    { fullName: 'Nguyễn Tuấn Vinh', email: 'tuanvinh2402@gmail.com' },
    { fullName: 'Nguyễn Đức Bảo Lâm', email: 'lam01662052827@gmail.com' },
    { fullName: 'Nguyễn Đức Huy', email: 'quanvu1497163@gmail.com' },
    { fullName: 'Trương Đoàn Viên', email: 'vientruongdoan@gmail.com' },
    { fullName: 'Nguyễn Huy Phong', email: 'touman876@gmail.com' },
    { fullName: 'Nguyễn Đoàn Nhật Đăng', email: 'nhatdang23092006@gmail.com' },
    { fullName: 'Võ Gia Huy', email: 'huyvog6226@gmail.com' },
    { fullName: 'Dương Ngô', email: 'duongngo2209@gmail.com' },
    { fullName: 'Thuận Phan', email: 'tcp352006@gmail.com' },
    { fullName: 'Huỳnh Hân Đồng', email: 'huynhhandong@gmail.com' },
  ],
  7: [
    { fullName: 'Trương Đoàn Viên', email: 'vientruongdoan@gmail.com' },
    { fullName: 'Dương Ngô', email: 'duongngo2209@gmail.com' },
    { fullName: 'Võ Nhật Minh', email: 'nhatminhvo2311@gmail.com' },
    { fullName: 'Phạm Đức Phúc', email: 'ducphucdn2006@gmail.com' },
    { fullName: 'Trần Trọng Nghĩa', email: 'hs23t2@gmail.com' },
    { fullName: 'Nguyễn Tuấn Vinh', email: 'tuanvinh2402@gmail.com' },
    { fullName: 'Nguyễn Đức Bảo Lâm', email: 'lam01662052827@gmail.com' },
    { fullName: 'Phạm Hoàng Tuấn', email: 'phamhoangtuanqn@gmail.com' },
    { fullName: 'Nguyễn Đức Huy', email: 'quanvu1497163@gmail.com' },
    { fullName: 'Võ Gia Huy', email: 'huyvog6226@gmail.com' },
    { fullName: 'Huỳnh Minh Khang', email: 'khanghuynh0245@gmail.com' },
  ],
  5: [
    { fullName: 'Trương Đoàn Viên', email: 'vientruongdoan@gmail.com' },
    { fullName: 'Dương Ngô', email: 'duongngo2209@gmail.com' },
    { fullName: 'Trần Trọng Nghĩa', email: 'hs23t2@gmail.com' },
    { fullName: 'Nguyễn Tuấn Vinh', email: 'tuanvinh2402@gmail.com' },
    { fullName: 'Nguyễn Đức Bảo Lâm', email: 'lam01662052827@gmail.com' },
    { fullName: 'Phạm Hoàng Tuấn', email: 'phamhoangtuanqn@gmail.com' },
    { fullName: 'Nguyễn Đức Huy', email: 'quanvu1497163@gmail.com' },
    { fullName: 'Võ Gia Huy', email: 'huyvog6226@gmail.com' },
    { fullName: 'Võ Đức Trí', email: 'voductri88714@gmail.com' },
    { fullName: 'Huỳnh Hân Đồng', email: 'huynhhandong@gmail.com' },
    { fullName: 'Huỳnh Minh Khang', email: 'khanghuynh0245@gmail.com' },
  ],
  2: [
    { fullName: 'Nguyễn Hoàng Minh', email: 'nguyenminh150906@gmail.com' },
    { fullName: 'Phạm Đức Phúc', email: 'ducphucdn2006@gmail.com' },
    { fullName: 'Võ Nhật Minh', email: 'nhatminhvo2311@gmail.com' },
    { fullName: 'Nguyễn Đức Bảo Lâm', email: 'lam01662052827@gmail.com' },
    { fullName: 'Phạm Hoàng Tuấn', email: 'phamhoangtuanqn@gmail.com' },
    { fullName: 'Nguyễn Đức Huy', email: 'quanvu1497163@gmail.com' },
    { fullName: 'Trương Đoàn Viên', email: 'vientruongdoan@gmail.com' },
    { fullName: 'Nguyễn Huy Phong', email: 'touman876@gmail.com' },
    { fullName: 'Nguyễn Đoàn Nhật Đăng', email: 'nhatdang23092006@gmail.com' },
    { fullName: 'Võ Đức Trí', email: 'voductri88714@gmail.com' },
    { fullName: 'Thuận Phan', email: 'tcp352006@gmail.com' },
    { fullName: 'Dương Ngô', email: 'duongngo2209@gmail.com' },
    { fullName: 'Huỳnh Hân Đồng', email: 'huynhhandong@gmail.com' },
    { fullName: 'Huỳnh Minh Khang', email: 'khanghuynh0245@gmail.com' },
  ],
  11: [
    { fullName: 'Nguyễn Huy Phong', email: 'touman876@gmail.com' },
    { fullName: 'Trần Trọng Nghĩa', email: 'hs23t2@gmail.com' },
    { fullName: 'Võ Nhật Minh', email: 'nhatminhvo2311@gmail.com' },
    { fullName: 'Phạm Hoàng Tuấn', email: 'phamhoangtuanqn@gmail.com' },
    { fullName: 'Nguyễn Đức Huy', email: 'quanvu1497163@gmail.com' },
    { fullName: 'Nguyễn Đoàn Nhật Đăng', email: 'nhatdang23092006@gmail.com' },
    { fullName: 'Võ Đức Trí', email: 'voductri88714@gmail.com' },
    { fullName: 'Thuận Phan', email: 'tcp352006@gmail.com' },
    { fullName: 'Dương Ngô', email: 'duongngo2209@gmail.com' },
    { fullName: 'Huỳnh Hân Đồng', email: 'huynhhandong@gmail.com' },
    { fullName: 'Huỳnh Minh Khang', email: 'khanghuynh0245@gmail.com' },
  ],
};
