// Danh sách ứng viên pass vòng 1
export const studentList = [
    {
        full_name: "Nguyễn Tố Uyên",
        student_code: "SE210179",
        major: "Software Engineering",
        phone: "0839211848",
        email: "athurconandoyle1859@gmail.com",
        semester: "TRS4",
    },
    {
        full_name: "Đỗ Thiết Thạch",
        student_code: "SE211156",
        major: "Software Engineering",
        phone: "0354314095",
        email: "thietthachdo@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Đạt Nguyễn",
        student_code: "SE190210",
        major: "Artificial Intelligence",
        phone: "0392447785",
        email: "nguyenvotiendat88@gmail.com",
        semester: "CN1",
    },
    {
        full_name: "Bảo Huỳnh Gia",
        student_code: "SE204913",
        major: "Artificial Intelligence",
        phone: "0335339691",
        email: "huynhgiabao2718@gmail.com",
        semester: "CN1",
    },
    {
        full_name: "Phú Nguyễn",
        student_code: "SE210043",
        major: "Software Engineering",
        phone: "0372240629",
        email: "ngvphu235e@gmail.com",
        semester: "TRS5",
    },
    {
        full_name: "Tạ Anh Đức",
        student_code: "SE201404",
        major: "Software Engineering",
        phone: "0948470962",
        email: "taanhduc15126@gmail.com",
        semester: "CN3",
    },
    {
        full_name: "Phạm Bảo",
        student_code: "SE211866",
        major: "Software Engineering",
        phone: "0834800913",
        email: "bao1342007@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Lê Khả Hoàng",
        student_code: "SE211377",
        major: "Software Engineering",
        phone: "0372804233",
        email: "lekhahoang5@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Lê Khả Huy",
        student_code: "SE211591",
        major: "Software Engineering",
        phone: "0337294790",
        email: "lekhahuy9@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Ho An",
        student_code: "SE201566",
        major: "Software Engineering",
        phone: "0865343056",
        email: "holethienan30102006@gmail.com",
        semester: "CN2",
    },
    {
        full_name: "Kiệt Lưu Hoàng Anh",
        student_code: "SE211135",
        major: "Software Engineering",
        phone: "0796333099",
        email: "kietluuhoanganh@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Nguyễn Minh Quân",
        student_code: "SE210130",
        major: "Artificial Intelligence",
        phone: "0777820470",
        email: "quannmdt@gmail.com",
        semester: "CN1",
    },
    {
        full_name: "Nguyễn Hưng Hiển",
        student_code: "SE210117",
        major: "Software Engineering",
        phone: "0327278654",
        email: "nguyenhunghien2928@gmail.com",
        semester: "TRS5",
    },
    {
        full_name: "Trần Ngọc Xuân Phúc",
        student_code: "SE211470",
        major: "Information Systems",
        phone: "0988774458",
        email: "tranngocxuanphuc307@gmail.com",
        semester: "LUK1",
    },
    {
        full_name: "Trần Anh",
        student_code: "SE211960",
        major: "Artificial Intelligence",
        phone: "0903909385",
        email: "doananhtran242007@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Nguyễn Tú",
        student_code: "SE210741",
        major: "Software Engineering",
        phone: "0326153807",
        email: "tu5249949@gmail.com",
        semester: "CN3",
    },
    {
        full_name: "Phan Tường Quân",
        student_code: "SE211201",
        major: "Software Engineering",
        phone: "0867377630",
        email: "pquan2212@gmail.com",
        semester: "CN1",
    },
    {
        full_name: "Nguyen Tien Khai",
        student_code: "SE212092",
        major: "Software Engineering",
        phone: "0982524572",
        email: "khaithichnhon@gmail.com",
        semester: "TRS4",
    },
    {
        full_name: "Trần Lê Anh Quân",
        student_code: "SE200441",
        major: "Software Engineering",
        phone: "0386684270",
        email: "tranquanlxag1990@gmail.com",
        semester: "CN2",
    },
    {
        full_name: "Minh Nguyễn",
        student_code: "SE210756",
        major: "Artificial Intelligence",
        phone: "0785319939",
        email: "100catcatcat100@gmail.com",
        semester: "CN1",
    },
    {
        full_name: "Nguyễn Cao Tiến Đạt",
        student_code: "SE211611",
        major: "Software Engineering",
        phone: "0942790808",
        email: "datnguyencaotien@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Lâm Hoàng An",
        student_code: "SE201018",
        major: "Software Engineering",
        phone: "0983699291",
        email: "lamhoangan612@gmail.com",
        semester: "CN1",
    },
    {
        full_name: "Phan Phượng",
        student_code: "SE210452",
        major: "Artificial Intelligence",
        phone: "0877227390",
        email: "phankimphuong100102@gmail.com",
        semester: "LUK1",
    },
    {
        full_name: "Trịnh Tâm",
        student_code: "SE203367",
        major: "Software Engineering",
        phone: "0365148258",
        email: "trinhthiminhtam8122@gmail.com",
        semester: "CN2",
    },
    {
        full_name: "Võ Thắng",
        student_code: "SE200932",
        major: "Artificial Intelligence",
        phone: "0394729112",
        email: "thanhtuan21062000@gmail.com",
        semester: "CN2",
    },
    {
        full_name: "Minh Nhật Nguyễn Hoàng",
        student_code: "SE211601",
        major: "Software Engineering",
        phone: "0901893756",
        email: "minhnhat071612@gmail.com",
        semester: "LUK3",
    },
    {
        full_name: "Nguyễn Hảo",
        student_code: "SE210946",
        major: "Information Assurance",
        phone: "0919653426",
        email: "luzmiuforerver@gmail.com",
        semester: "LUK3",
    },
    {
        full_name: "Dương Thiện Phú",
        student_code: "SE210810",
        major: "Integrated Circuit",
        phone: "0982780627",
        email: "dthienphu160@gmail.com",
        semester: "TRS4",
    },
    {
        full_name: "Ngoc Phuc Nguyen",
        student_code: "SE203055",
        major: "Software Engineering",
        phone: "0932720343",
        email: "phuchcm2006@gmail.com",
        semester: "CN2",
    },
    {
        full_name: "Viet Nguyen",
        student_code: "SE211888",
        major: "Software Engineering",
        phone: "0327777596",
        email: "viet2007ht@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Đăng Lê",
        student_code: "SE201183",
        major: "Software Engineering",
        phone: "0843339068",
        email: "ledangminh1206@gmail.com",
        semester: "CN1",
    },
    {
        full_name: "Mai Hiếu",
        student_code: "SE200972",
        major: "Software Engineering",
        phone: "0965607840",
        email: "xuanhieubato@gmail.com",
        semester: "CN3",
    },
    {
        full_name: "Lê Thị Minh Tâm",
        student_code: "SE201843",
        major: "Software Engineering",
        phone: "0815156094",
        email: "lethiminhtam072006@gmail.com",
        semester: "TRS5",
    },
    {
        full_name: "Lê Tuấn Anh Đàm",
        student_code: "SE204111",
        major: "Software Engineering",
        phone: "0908957939",
        email: "damletuananh123@gmail.com",
        semester: "CN2",
    },
    {
        full_name: "Nam Võ",
        student_code: "SE211766",
        major: "Software Engineering",
        phone: "0944994562",
        email: "hoangnamvopham786@gmail.com",
        semester: "TRS4",
    },
    {
        full_name: "Trần Trung Tín",
        student_code: "SE201619",
        major: "Artificial Intelligence",
        phone: "0945093680",
        email: "trungtin1218@gmail.com",
        semester: "CN2",
    },
    {
        full_name: "Trần Vy",
        student_code: "SE210918",
        major: "Software Engineering",
        phone: "0327338321",
        email: "tttbeo.007@gmail.com",
        semester: "LUK1",
    },
    {
        full_name: "Vũ Tuấn",
        student_code: "SE211093",
        major: "Integrated Circuit",
        phone: "0703421670",
        email: "vuminhtuan5264@gmail.com",
        semester: "LUK3",
    },
    {
        full_name: "Ngô Hân",
        student_code: "SE203677",
        major: "Software Engineering",
        phone: "0901675018",
        email: "hanngo416@gmail.com",
        semester: "CN3",
    },
    {
        full_name: "Duy Trần",
        student_code: "SE200516",
        major: "Software Engineering",
        phone: "0823963128",
        email: "tranvuhaiduy2006hg@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Chu Cường",
        student_code: "SE210364",
        major: "Software Engineering",
        phone: "0965393922",
        email: "minhcuongchu1907@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Bình Nguyễn Văn Gia",
        student_code: "SE203555",
        major: "Software Engineering",
        phone: "0869089715",
        email: "nguyenvangiabinh22072006@gmail.com",
        semester: "CN2",
    },
    {
        full_name: "Trần Tường",
        student_code: "SE211449",
        major: "Information Systems",
        phone: "0901776487",
        email: "khanhtuong2302@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Nguyễn Vy",
        student_code: "SE210777",
        major: "Artificial Intelligence",
        phone: "0963848771",
        email: "myvy0807@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Nhân Chí",
        student_code: "SE203237",
        major: "Software Engineering",
        phone: "0394654576",
        email: "buiphamchinhan@gmail.com",
        semester: "CN3",
    },
    {
        full_name: "Văn Bình Nguyễn",
        student_code: "SE211968",
        major: "Software Engineering",
        phone: "0373450305",
        email: "nguyenvanbinh542007@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Nguyễn Kim Tiến Đạt",
        student_code: "SE210773",
        major: "Software Engineering",
        phone: "0961539153",
        email: "nguyentiendat7505@gmail.com",
        semester: "TRS5",
    },
    {
        full_name: "Nguyễn Khôi Nguyên",
        student_code: "SE211898",
        major: "Software Engineering",
        phone: "0984083792",
        email: "khoinguyenperfect@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Đạt Vũ",
        student_code: "SE211953",
        major: "Software Engineering",
        phone: "0344095707",
        email: "vumaianhdat07@gmail.com",
        semester: "LUK3",
    },
    {
        full_name: "Nguyên Võ Lê Khôi",
        student_code: "SE211914",
        major: "Software Engineering",
        phone: "0375669481",
        email: "nguyen13032007@gmail.com",
        semester: "TRS5",
    },
    {
        full_name: "Quoc Anh Nguyen",
        student_code: "SE211043",
        major: "Software Engineering",
        phone: "0789849037",
        email: "mercedecpeek502@gmail.com",
        semester: "CN1",
    },
    {
        full_name: "Minh Trọng Hoàng",
        student_code: "SE211927",
        major: "Software Engineering",
        phone: "0972672466",
        email: "htrong606@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Dư Hảo",
        student_code: "SE212030",
        major: "Artificial Intelligence",
        phone: "0902411641",
        email: "donghao2209@gmail.com",
        semester: "CN1",
    },
    {
        full_name: "Lợi Nguyễn Tấn",
        student_code: "SE211059",
        major: "Software Engineering",
        phone: "0778653868",
        email: "ishisi.ainari@gmail.com",
        semester: "TRS5",
    },
    {
        full_name: "Phạm Đỗ Minh Đăng",
        student_code: "SE211596",
        major: "Information Assurance",
        phone: "0789997446",
        email: "minhdang200718@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Văng Khánh Khuyên",
        student_code: "SE200481",
        major: "Software Engineering",
        phone: "0702946163",
        email: "diechahien@gmail.com",
        semester: "CN2",
    },
    {
        full_name: "Nguyễn Thái Huy",
        student_code: "SE211528",
        major: "Artificial Intelligence",
        phone: "0858835036",
        email: "thaihuyxbox@gmail.com",
        semester: "LUK3",
    },
    {
        full_name: "Nguyen Van Quoc Bao",
        student_code: "SE201682",
        major: "Software Engineering",
        phone: "0399556929",
        email: "quocbao.nguyen16102006@gmail.com",
        semester: "CN2",
    },
    {
        full_name: "Bình Đỗ Thanh",
        student_code: "SE210474",
        major: "Software Engineering",
        phone: "0903960285",
        email: "dothanhbinh102007@gmail.com",
        semester: "LUK3",
    },
    {
        full_name: "Thành Đậu Đức",
        student_code: "SE211107",
        major: "Artificial Intelligence",
        phone: "0866285370",
        email: "dauducthanh240907@gmail.com",
        semester: "LUK1",
    },
    {
        full_name: "nguyen khang",
        student_code: "SE210496",
        major: "Software Engineering",
        phone: "0976237876",
        email: "khangnguyen123cvn@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Triết Nguyễn",
        student_code: "SE211615",
        major: "Software Engineering",
        phone: "0916413778",
        email: "nguyenthanhtrieta@gmail.com",
        semester: "LUK4",
    },
    {
        full_name: "Bui Trong",
        student_code: "SE212026",
        major: "Integrated Circuit",
        phone: "0901671494",
        email: "buiphuoctrong.semi@gmail.com",
        semester: "CN1",
    },
    {
        full_name: "Nguyễn Văn Duy Nhân",
        student_code: "SE211932",
        major: "Artificial Intelligence",
        phone: "0915219213",
        email: "nhannguyen120216@gmail.com",
        semester: "TRS4",
    },
    {
        full_name: "Thành Trần",
        student_code: "SE210041",
        major: "Software Engineering",
        phone: "0335021778",
        email: "trancaothanhbtm9@gmail.com",
        semester: "TRS4",
    },
    {
        full_name: "Huy Võ",
        student_code: "SE210556",
        major: "Software Engineering",
        phone: "0908008416",
        email: "vohuy19042007@gmail.com",
        semester: "CN1",
    },
    {
        full_name: "Huyền Ngô Xuân",
        student_code: "SE210768",
        major: "Software Engineering",
        phone: "0398532284",
        email: "lethihannc@gmail.com",
        semester: "LUK1",
    },
    {
        full_name: "Nguyen Lam",
        student_code: "SE210380",
        major: "Artificial Intelligence",
        phone: "0869200419",
        email: "jhwei521@gmail.com",
        semester: "TRS6",
    },
    {
        full_name: "Le Quang",
        student_code: "SE204789",
        major: "Software Engineering",
        phone: "0974920299",
        email: "quang221208642@gmail.com",
        semester: "CN1",
    },
    {
        full_name: "Chánh Lê",
        student_code: "SE210518",
        major: "Software Engineering",
        phone: "0968755719",
        email: "chanhle1907@gmail.com",
        semester: "CN1",
    },
];
